# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker

networking:
  # here is a custom Service CIDR and Pod CIDR setup:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"

